/// Static reference data for [PrescriptionParserService] — pulled out into
/// its own file purely to keep the parser file itself focused on parsing
/// *logic* rather than several hundred lines of drug names. Nothing in
/// here is parsing behavior; it's just the dictionaries that behavior
/// looks things up against. Extend [DrugKnowledgeBase.knownDrugs] as you
/// encounter drugs it doesn't recognize.
class DrugKnowledgeBase {
  DrugKnowledgeBase._();

  /// Fallback drug dictionary used only when no database-backed list is
  /// passed in via `PrescriptionParserService.parse`'s `drugDictionary`
  /// parameter (e.g. offline scans, or before [MedicineDictionaryService]
  /// is wired up). Prefer passing this pharmacy's real medicine list from
  /// the database — see [MedicineDictionaryService] — since matching
  /// against what this pharmacy actually stocks is meaningfully more
  /// accurate than matching against every generic drug name below.
  static const List<String> knownDrugs = [
    'paracetamol',
    'biogesic',
    'amoxicillin',
    'amoxicillin trihydrate',
    'co-amoxiclav',
    'augmentin',
    'azithromycin',
    'zithromax',
    'cefalexin',
    'cephalexin',
    'ciprofloxacin',
    'clindamycin',
    'metformin',
    'glucophage',
    'gliclazide',
    'losartan',
    'losartan potassium',
    'amlodipine',
    'atorvastatin',
    'simvastatin',
    'rosuvastatin',
    'omeprazole',
    'esomeprazole',
    'ranitidine',
    'cetirizine',
    'loratadine',
    'diphenhydramine',
    'benadryl',
    'mefenamic acid',
    'ponstan',
    'ibuprofen',
    'celecoxib',
    'salbutamol',
    'ventolin',
    'montelukast',
    'budesonide',
    'multivitamins',
    'ferrous sulfate',
    // Chemical-formula shorthand doctors write instead of the full
    // generic name ("Rx FeSO4 tab #30"). Kept here too for the offline
    // fallback path, but the actual fix that makes this resolve against
    // EITHER dictionary (this fallback list or the live backend catalog)
    // lives in DrugAbbreviations.resolve, called from _fuzzyMatchDrug in
    // prescription_parser_service.dart — plain fuzzy similarity alone was
    // never going to match "feso4" (or the raw OCR output "fesov")
    // to "ferrous sulfate" regardless of which list it's searched
    // against.
    'feso4',
    'folic acid',
    'calcium carbonate',
    'metoprolol',
    'bisoprolol',
    'carvedilol',
    'clopidogrel',
    'aspirin',
    'furosemide',
    'hydrochlorothiazide',
    'spironolactone',
    'insulin',
    'levothyroxine',
    'prednisone',
    'prednisolone',
    'tranexamic acid',
    'domperidone',
    'loperamide',
    'oral rehydration salts',
    'metronidazole',
    'fluconazole',
    'hydroxyzine',
    'diazepam',
    'tramadol',
    'dextromethorphan',
    'ambroxol',
    'carbocisteine',
    'phenylephrine',
    'guaifenesin',
    'acetaminophen',
    'adrenaline',
    'albuterol',
    'alfuzosin',
    'allopurinol',
    'alprazolam',
    'amlodipine',
    'amoxicillin',
    'amphotericin b',
    'ampicillin',
    'anastrozole',
    'atenolol',
    'atorvastatin',
    'azithromycin',
    'beclomethasone',
    'benztropine',
    'bisoprolol',
    'bleomycin',
    'budesonide',
    'buspirone',
    'cabergoline',
    'candesartan',
    'carbamazepine',
    'carisoprodol',
    'ceftriaxone',
    'celecoxib',
    'cetirizine',
    'chlorambucil',
    'chlorhexidine',
    'chloroquine',
    'ciprofloxacin',
    'clarithromycin',
    'clonazepam',
    'clopidogrel',
    'codeine',
    'corticosteroid',
    'cyclophosphamide',
    'dabigatran',
    'dapsone',
    'deferoxamine',
    'delavirdine',
    'desmopressin',
    'dexamethasone',
    'dexketoprofen',
    'diazepam',
    'diclofenac',
    'digoxin',
    'diltiazem',
    'dimenhydrinate',
    'diphenhydramine',
    'doxycycline',
    'dronedarone',
    'drospirenone',
    'ebastine',
    'enalapril',
    'enoxaparin',
    'epinephrine',
    'erythromycin',
    'esomeprazole',
    'ethambutol',
    'ethinylestradiol',
    'etoposide',
    'fexofenadine',
    'finasteride',
    'fluticasone',
    'fluconazole',
    'fluoxetine',
    'folic acid',
    'formoterol',
    'fosinopril',
    'furosemide',
    'gabapentin',
    'guaifenesin',
    'haloperidol',
    'hydrochlorothiazide',
    'hydrocortisone',
    'hydralazine',
    'hydroxychloroquine',
    'hydroxyzine',
    'ibuprofen',
    'indomethacin',
    'infliximab',
    'insulin',
    'iron',
    'ivermectin',
    'ketoconazole',
    'ketorolac',
    'lamivudine',
    'lansoprazole',
    'levothyroxine',
    'lidocaine',
    'lisinopril',
    'loratadine',
    'losartan',
    'loperamide',
    'lorazepam',
    'lovastatin',
    'magnesium',
    'mebendazole',
    'mefenamic acid',
    'melatonin',
    'metformin',
    'metoclopramide',
    'metoprolol',
    'metronidazole',
    'miconazole',
    'midazolam',
    'minoxidil',
    'mirtazapine',
    'mitomycin',
    'mometasone',
    'montelukast',
    'morphine',
    'multivitamins',
    'nadolol',
    'nateglinide',
    'nebivolol',
    'neomycin',
    'nicardipine',
    'nifedipine',
    'nitroglycerin',
    'norfloxacin',
    'nystatin',
    'omeprazole',
    'ondansetron',
    'oral rehydration salts',
    'orlistat',
    'oseltamivir',
    'oxcarbazepine',
    'pantoprazole',
    'paracetamol',
    'praziquantel',
    'prednisolone',
    'prednisone',
    'procainamide',
    'prochlorperazine',
    'propranolol',
    'pseudoephedrine',
    'quinine',
    'rabies vaccine',
    'ranitidine',
    'rifampicin',
    'rimantadine',
    'rosuvastatin',
    'salmeterol',
    'salbutamol',
    'sertraline',
    'sildenafil',
    'simvastatin',
    'sodium bicarbonate',
    'sulfamethoxazole',
    'sulfasalazine',
    'sumatriptan',
    'tacrolimus',
    'tamsulosin',
    'telmisartan',
    'terbinafine',
    'tetracycline',
    'thiabendazole',
    'thiamine',
    'tiotropium',
    'tobramycin',
    'tramadol',
    'tranexamic acid',
    'tretinoin',
    'triamcinolone',
    'trimethoprim',
    'valsartan',
    'vitamin a',
    'vitamin b1',
    'vitamin b12',
    'vitamin b2',
    'vitamin b6',
    'vitamin c',
    // Doctors overwhelmingly write the generic name "Ascorbic Acid"
    // on Rx pads rather than "Vitamin C" — without its own entry this
    // fuzzy-matched too poorly against "vitamin c" (very different
    // strings) to count as a known drug, which meant a line with no
    // dosage/quantity of its own (see the nearby name+dosage line
    // merge above) had nothing to fall back on and silently vanished.
    'ascorbic acid',
    'vitamin d',
    'vitamin e',
    'vitamin k1',
    'warfarin',
    'xylometazoline',
    'zidovudine',
    'zinc',
    'zolmitriptan',
    'zolpidem',
    'zoledronic acid',
  ];

  /// Frequency shorthand doctors write, normalized to a readable form.
  /// Longer keys are matched before shorter ones so e.g. "q12h" isn't
  /// swallowed by a looser pattern.
  static const Map<String, String> frequencyMap = {
    'once daily': 'once daily',
    'once a day': 'once daily',
    'twice daily': 'twice daily',
    'twice a day': 'twice daily',
    '3x daily': '3x daily',
    'thrice a day': '3x daily',
    'three times a day': '3x daily',
    '4x daily': '4x daily',
    'four times a day': '4x daily',
    'at bedtime': 'at bedtime',
    // 'as needed': 'as needed',
    'before meals': 'before meals',
    'after meals': 'after meals',
    'every 4 hours': 'every 4 hours',
    'every 6 hours': 'every 6 hours',
    'every 8 hours': 'every 8 hours',
    'every 12 hours': 'every 12 hours',
    'q4h': 'every 4 hours',
    'q6h': 'every 6 hours',
    'q8h': 'every 8 hours',
    'q12h': 'every 12 hours',
    'od': 'once daily',
    'qd': 'once daily',
    'bid': 'twice daily',
    'bd': 'twice daily',
    'tid': '3x daily',
    'tds': '3x daily',
    'qid': '4x daily',
    'qds': '4x daily',
    'hs': 'at bedtime',
    'qhs': 'at bedtime',
    // 'prn': 'as needed',
    'ac': 'before meals',
    'pc': 'after meals',
    'stat': 'immediately',
  };
}
